---
- name: Add hosts entries to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ host['ip_address'] }}"
    line: "{{ host['ip_address'] }}   {{ host['canonical_name'] }} {{ host['aliases'] | default('') | join(' ') }}"
    state: present
  with_items: "{{ hosts_entries }}"
  become: true
  loop_control:
    loop_var: host
