---
- import_tasks: hosts.yml

- import_tasks: proxy.yml

- name: Gather package facts
  package_facts:
    manager: auto

- import_tasks: disable-selinux.yml
  when:
    - disable_selinux | bool
    - "'selinux' in ansible_facts.packages"

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  when:
    - disable_firewalld | bool
    - "'firewalld' in ansible_facts.packages"
  become: true
