---
- import_tasks: hosts.yml

- import_tasks: proxy.yml

- name: Gather package facts
  package_facts:
    manager: auto

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: "'firewalld' in ansible_facts.packages"
  become: true

- name: Set selinux in permissive mode until the machine is rebooted
  shell: setenforce 0 || true
  changed_when: false
  when: "'selinux' in ansible_facts.packages"
  become: true

- name: Disable selinux at next reboot
  selinux:
    state: disabled
  become: true
