---
- name: Configure http_proxy for windows (machine environment)
  win_environment:
    name: http_proxy
    value: "{{ http_proxy }}"
    level: machine
    state: present
  when: http_proxy is defined

- name: Configure https_proxy for windows (machine environment)
  win_environment:
    name: https_proxy
    value: "{{ https_proxy }}"
    level: machine
    state: present
  when: https_proxy is defined

- name: Configure ftp_proxy for windows (machine environment)
  win_environment:
    name: ftp_proxy
    value: "{{ ftp_proxy }}"
    level: machine
    state: present
  when: ftp_proxy is defined

- name: Configure no_proxy for windows (machine environment)
  win_environment:
    name: no_proxy
    value: "{{ no_proxy }}"
    level: machine
    state: present
  when: no_proxy is defined

- name: Configure IE proxy settings to apply to all users
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
    name: ProxySettingsPerUser
    data: "0"
    type: dword
    state: present

- name: Configure IE proxy
  win_inet_proxy:
    proxy: "{{ win_inet_proxy | default(omit) }}"
    bypass: "{{ win_inet_bypass | default(omit) }}"

# This should be done after setting the IE proxy with win_inet_proxy
- name: Import IE proxy configuration to WinHTTP
  win_http_proxy:
    source: ie
